# Generated by Django 6.1.1 on 2026-09-27 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PastPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_code', models.CharField(max_length=20)),
                ('module_name', models.CharField(max_length=200)),
                ('faculty', models.CharField(blank=True, choices=[('science_it', 'Computer Science & IT'), ('math', 'Mathematical Sciences'), ('commerce', 'Commerce, Administration & Law'), ('arts', 'Arts'), ('education', 'Education')], max_length=30)),
                ('year', models.PositiveSmallIntegerField()),
                ('semester', models.PositiveSmallIntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2')])),
                ('paper_type', models.CharField(choices=[('exam', 'Examination'), ('test', 'Test'), ('quiz', 'Quiz'), ('assignment', 'Assignment')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('file', models.FileField(upload_to='past_papers/%Y/')),
                ('file_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year', 'module_code'],
            },
        ),
    ]
